
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 10 17:16:07 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Sat Jan 10 17:16:07 CET 2026
  */
public class MPParserError extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParserError() {super();}

  /** Constructor which sets the default scanner. */
  public MPParserError(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\046\000\002\003\005\000\002\002\004\000\002\003" +
    "\005\000\002\004\006\000\002\004\006\000\002\005\004" +
    "\000\002\005\003\000\002\007\006\000\002\007\006\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\006\005\000\002\006\003\000\002\006" +
    "\005\000\002\011\003\000\002\011\003\000\002\012\005" +
    "\000\002\014\003\000\002\014\006\000\002\014\006\000" +
    "\002\014\005\000\002\014\004\000\002\014\003\000\002" +
    "\015\005\000\002\015\005\000\002\015\003\000\002\016" +
    "\003\000\002\016\003\000\002\013\012\000\002\013\012" +
    "\000\002\013\011\000\002\013\010\000\002\013\007\000" +
    "\002\013\006\000\002\013\005\000\002\013\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\100\000\004\004\005\001\002\000\004\002\102\001" +
    "\002\000\004\011\007\001\002\000\006\003\101\016\100" +
    "\001\002\000\004\017\010\001\002\000\004\025\070\001" +
    "\002\000\006\013\ufffb\017\ufffb\001\002\000\006\013\014" +
    "\017\013\001\002\000\006\025\070\026\030\001\002\000" +
    "\006\003\052\023\053\001\002\000\010\003\ufff0\012\ufff0" +
    "\027\ufff0\001\002\000\010\003\ufff3\012\ufff3\027\ufff3\001" +
    "\002\000\010\003\ufff1\012\ufff1\027\ufff1\001\002\000\010" +
    "\003\023\012\024\027\022\001\002\000\006\013\ufffc\017" +
    "\ufffc\001\002\000\010\003\026\013\014\017\025\001\002" +
    "\000\012\003\ufffd\012\ufffd\016\ufffd\027\ufffd\001\002\000" +
    "\012\003\ufffe\012\ufffe\016\ufffe\027\ufffe\001\002\000\004" +
    "\026\030\001\002\000\010\003\ufff2\012\ufff2\027\ufff2\001" +
    "\002\000\010\003\ufff4\012\ufff4\027\ufff4\001\002\000\012" +
    "\003\034\014\036\017\033\020\031\001\002\000\016\003" +
    "\uffe4\012\uffe4\021\uffe4\022\uffe4\024\uffe4\027\uffe4\001\002" +
    "\000\014\003\uffe6\012\uffe6\021\uffe6\022\uffe6\027\uffe6\001" +
    "\002\000\016\003\uffe5\012\uffe5\021\uffe5\022\uffe5\024\uffe5" +
    "\027\uffe5\001\002\000\010\003\uffe9\012\uffe9\027\uffe9\001" +
    "\002\000\010\003\uffef\012\uffef\027\uffef\001\002\000\006" +
    "\003\044\023\045\001\002\000\014\003\uffee\012\uffee\021" +
    "\040\022\041\027\uffee\001\002\000\006\017\033\020\031" +
    "\001\002\000\006\017\033\020\031\001\002\000\014\003" +
    "\uffe7\012\uffe7\021\uffe7\022\uffe7\027\uffe7\001\002\000\014" +
    "\003\uffe8\012\uffe8\021\uffe8\022\uffe8\027\uffe8\001\002\000" +
    "\010\003\uffea\012\uffea\027\uffea\001\002\000\010\003\047" +
    "\017\033\020\031\001\002\000\006\003\051\024\050\001" +
    "\002\000\010\003\uffeb\012\uffeb\027\uffeb\001\002\000\010" +
    "\003\uffed\012\uffed\027\uffed\001\002\000\010\003\uffec\012" +
    "\uffec\027\uffec\001\002\000\010\003\uffdc\012\uffdc\027\uffdc" +
    "\001\002\000\006\003\055\017\054\001\002\000\006\003" +
    "\057\015\056\001\002\000\010\003\uffdd\012\uffdd\027\uffdd" +
    "\001\002\000\006\003\061\017\060\001\002\000\010\003" +
    "\uffde\012\uffde\027\uffde\001\002\000\006\003\063\024\062" +
    "\001\002\000\010\003\uffdf\012\uffdf\027\uffdf\001\002\000" +
    "\006\003\065\030\064\001\002\000\010\003\uffe0\012\uffe0" +
    "\027\uffe0\001\002\000\006\003\066\011\007\001\002\000" +
    "\010\003\uffe1\012\uffe1\027\uffe1\001\002\000\010\003\uffe2" +
    "\012\uffe2\027\uffe2\001\002\000\010\003\uffe3\012\uffe3\027" +
    "\uffe3\001\002\000\012\005\071\006\075\007\072\010\074" +
    "\001\002\000\006\003\ufff8\027\ufff8\001\002\000\006\003" +
    "\ufff6\027\ufff6\001\002\000\006\003\077\027\076\001\002" +
    "\000\006\003\ufff5\027\ufff5\001\002\000\006\003\ufff7\027" +
    "\ufff7\001\002\000\006\013\ufffa\017\ufffa\001\002\000\006" +
    "\013\ufff9\017\ufff9\001\002\000\004\002\001\001\002\000" +
    "\004\002\uffff\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\100\000\004\003\003\001\001\000\002\001\001\000" +
    "\004\004\005\001\001\000\002\001\001\000\006\005\011" +
    "\007\010\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\006\017\007\020\011\015\012\016\013\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\026\012\016\013\014\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\014\034\015\036\016" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\016\042\001\001\000\004" +
    "\016\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\066\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\072\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParserError$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParserError$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParserError$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



public int errNo = 0;
   
   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new MPLexer( file );
		   MPParserError parser = new MPParserError( scanner );
		   parser.parse();
		   if ( parser.errNo == 0 )
		      System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
		   else
		      System.out.println( "Analiza zavrsena. Broj gresaka: " + parser.errNo );
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }
   
   public void syntax_error(Symbol cur_token)
   {
   	  
   }
   
   public void report_error(String message, Object info)
   {
   	   System.out.print( message );
   }
   
   public int getLine()
   {
   	  return (( MPLexer) getScanner()).getLine();
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParserError$actions {
  private final MPParserError parser;

  /** Constructor */
  CUP$MPParserError$actions(MPParserError parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParserError$do_action(
    int                        CUP$MPParserError$act_num,
    java_cup.runtime.lr_parser CUP$MPParserError$parser,
    java.util.Stack            CUP$MPParserError$stack,
    int                        CUP$MPParserError$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParserError$result;

      /* select the action based on the action number */
      switch (CUP$MPParserError$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ReadExpression ::= READ error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje '('");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // ReadExpression ::= READ LEFTPAR error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje prva promenljiva");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ReadExpression ::= READ LEFTPAR ID error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'in'");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ReadExpression ::= READ LEFTPAR ID IN error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje druga promenljiva");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ReadExpression ::= READ LEFTPAR ID IN ID error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje ')'");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ReadExpression ::= READ LEFTPAR ID IN ID RIGHTPAR error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'do'");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ReadExpression ::= READ LEFTPAR ID IN ID RIGHTPAR DO error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje blok");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ReadExpression ::= READ LEFTPAR ID IN ID RIGHTPAR DO Block 
            {
              Object RESULT = null;
		
				System.out.println("12");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(9/*ReadExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // PrimaryExpression ::= CONST 
            {
              Object RESULT = null;
		
				System.out.println("11");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*PrimaryExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // PrimaryExpression ::= ID 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(12/*PrimaryExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ArithmeticExpression ::= PrimaryExpression 
            {
              Object RESULT = null;
		
				System.out.println("10");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ArithmeticExpression ::= ArithmeticExpression MINUS PrimaryExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ArithmeticExpression ::= ArithmeticExpression PLUS PrimaryExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(11/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Expression ::= error 
            {
              Object RESULT = null;
		
			System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'open'"); 
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Expression ::= OPEN error 
            {
              Object RESULT = null;
		
			System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje '('"); 
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Expression ::= OPEN LEFTPAR error 
            {
              Object RESULT = null;
		
			System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje izraz"); 
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Expression ::= OPEN LEFTPAR PrimaryExpression error 
            {
              Object RESULT = null;
		
			System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje ')'"); 
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Expression ::= OPEN LEFTPAR PrimaryExpression RIGHTPAR 
            {
              Object RESULT = null;
		
				System.out.println("9");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Expression ::= ArithmeticExpression 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(10/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Assignment ::= ID ASSIGN Expression 
            {
              Object RESULT = null;
		
				System.out.println("8");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Statement ::= ReadExpression 
            {
              Object RESULT = null;
		
				System.out.println("7");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statement ::= Assignment 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statements ::= Statements SEMICOLON error 
            {
              Object RESULT = null;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje statement");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statements ::= Statement 
            {
              Object RESULT = null;
		
				System.out.println("6");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Statements ::= Statements SEMICOLON Statement 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Type ::= FILE 
            {
              Object RESULT = null;
		
				System.out.println("5");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= STRING 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= CHAR 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= INTEGER 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Var ::= ID COLON Type error 
            {
              Object RESULT = null;
		
				System.out.println( "Greska u liniji " + parser.getLine() + " Nedostaje ';'" );
				parser.errNo++;
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(5/*Var*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Var ::= ID COLON Type SEMICOLON 
            {
              Object RESULT = null;
		
				System.out.println("4");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(5/*Var*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VarList ::= Var 
            {
              Object RESULT = null;
		
				System.out.println("3");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(3/*VarList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VarList ::= VarList Var 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(3/*VarList*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Block ::= BEGIN VarList Statements error 
            {
              Object RESULT = null;
		
				System.out.println( "Greska u liniji " + parser.getLine() + " Nedostaje 'end' na kraju bloka" );
				parser.errNo++;
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Block ::= BEGIN VarList Statements END 
            {
              Object RESULT = null;
		
				System.out.println("2");
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= PROGRAM Block error 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).value;
		
				System.out.println("Greska u liniji " + parser.getLine() + " Nedostaje 'return' na kraju programa");
				parser.errNo++;
		
              CUP$MPParserError$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).value;
		RESULT = start_val;
              CUP$MPParserError$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParserError$parser.done_parsing();
          return CUP$MPParserError$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= PROGRAM Block RETURN 
            {
              Object RESULT = null;

              CUP$MPParserError$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParserError$stack.elementAt(CUP$MPParserError$top-0)).right, RESULT);
            }
          return CUP$MPParserError$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

