
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 10 17:16:07 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 9;
  public static final int SEMICOLON = 21;
  public static final int PLUS = 15;
  public static final int CHAR = 4;
  public static final int IN = 11;
  public static final int LEFTPAR = 17;
  public static final int FILE = 6;
  public static final int END = 8;
  public static final int RETURN = 12;
  public static final int RIGHTPAR = 18;
  public static final int COLON = 19;
  public static final int ID = 13;
  public static final int PROGRAM = 2;
  public static final int DO = 22;
  public static final int BEGIN = 7;
  public static final int STRING = 5;
  public static final int EOF = 0;
  public static final int MINUS = 16;
  public static final int CONST = 14;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int INTEGER = 3;
  public static final int OPEN = 10;
}

